# Generated by Django 5.1.4 on 2025-04-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('in Progress', 'in Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
    ]
